export enum UserConstants {
    FETCH_COURSES = '[COURSES]_FETCH_COURSES',
    FETCH_COURSES_OK = '[COURSES]_FETCH_COURSES_OK',
    FETCH_COURSES_FAIL = '[COURSES]_FETCH_COURSES_FAIL',
    CLEAR = '[COURSES]_CLEAR',
}